[package]
name = "expand"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parameterized = { path = "..", version = "0.1" }
